---
- name: Install MariaDB
  become: yes
  become_user: root
  yum:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python

- name: Setup my.cnf
  become: yes
  become_user: root
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK mariadb"
    dest: /etc/my.cnf
    content: |
      [mysqld]
      sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

- name: Restart mariadb
  become: yes
  become_user: root
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: yes

- name: Create isucon user on MySQL
  become: yes
  become_user: isucon
  mysql_user:
    login_user: root
    name: isucon
    password: isucon
    priv: "*.*:ALL"
    host: localhost
    state: present

- name: Stop mariadb
  become: yes
  become_user: root
  systemd:
    name: mariadb
    state: stopped
    daemon_reload: yes
